### ISSUE TITLE
Cache labelling results

### ISSUE THREAD

**Issue by Helveg** [dbbs-lab/arborize#14]
As @claudiacasellato suggested it could be beneficial to cache the labelling results; there are some considerations however:

* When multiple candidate types (#10) are considered the number of different combinatorial possibilities might surpass the cell count or atleast reduce caching efficiency.
* Caching many sets of labels might significantly increase the memory footprint and is useless to be retained during simulation.

The first consideration can be adressed by allowing a class attribute `cache_labels = False` to be set on the model by users who know they won't benefit from it. The second would require either a monkey patch of Patch so that when the simulated is started a cleanup phase can be held and the cache can be discarded. Another solution is a function the user can call to throw away the label cache. The manual function would allow people that don't use patch (but this isn't endorsed) to still throw away the cache before starting their sims. (And solution 1 could use this function during the cleanup phase)

**Comment by claudiacasellato** [comment]
I would go more for automatic discarding of label cache.. :)

**Comment by Helveg** [comment]
fixed by lowering the `Definition` into a `Schema` before building it
